# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/lgarczyn/p/rubik

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/lgarczyn/p/rubik

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/lgarczyn/p/rubik/CMakeFiles /Users/lgarczyn/p/rubik/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/lgarczyn/p/rubik/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named npuzzle

# Build rule for target.
npuzzle: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 npuzzle
.PHONY : npuzzle

# fast build rule for target.
npuzzle/fast:
	$(MAKE) -f CMakeFiles/npuzzle.dir/build.make CMakeFiles/npuzzle.dir/build
.PHONY : npuzzle/fast

CliOptParser.o: CliOptParser.cpp.o

.PHONY : CliOptParser.o

# target to build an object file
CliOptParser.cpp.o:
	$(MAKE) -f CMakeFiles/npuzzle.dir/build.make CMakeFiles/npuzzle.dir/CliOptParser.cpp.o
.PHONY : CliOptParser.cpp.o

CliOptParser.i: CliOptParser.cpp.i

.PHONY : CliOptParser.i

# target to preprocess a source file
CliOptParser.cpp.i:
	$(MAKE) -f CMakeFiles/npuzzle.dir/build.make CMakeFiles/npuzzle.dir/CliOptParser.cpp.i
.PHONY : CliOptParser.cpp.i

CliOptParser.s: CliOptParser.cpp.s

.PHONY : CliOptParser.s

# target to generate assembly for a file
CliOptParser.cpp.s:
	$(MAKE) -f CMakeFiles/npuzzle.dir/build.make CMakeFiles/npuzzle.dir/CliOptParser.cpp.s
.PHONY : CliOptParser.cpp.s

Heuristics.o: Heuristics.cpp.o

.PHONY : Heuristics.o

# target to build an object file
Heuristics.cpp.o:
	$(MAKE) -f CMakeFiles/npuzzle.dir/build.make CMakeFiles/npuzzle.dir/Heuristics.cpp.o
.PHONY : Heuristics.cpp.o

Heuristics.i: Heuristics.cpp.i

.PHONY : Heuristics.i

# target to preprocess a source file
Heuristics.cpp.i:
	$(MAKE) -f CMakeFiles/npuzzle.dir/build.make CMakeFiles/npuzzle.dir/Heuristics.cpp.i
.PHONY : Heuristics.cpp.i

Heuristics.s: Heuristics.cpp.s

.PHONY : Heuristics.s

# target to generate assembly for a file
Heuristics.cpp.s:
	$(MAKE) -f CMakeFiles/npuzzle.dir/build.make CMakeFiles/npuzzle.dir/Heuristics.cpp.s
.PHONY : Heuristics.cpp.s

Solver.o: Solver.cpp.o

.PHONY : Solver.o

# target to build an object file
Solver.cpp.o:
	$(MAKE) -f CMakeFiles/npuzzle.dir/build.make CMakeFiles/npuzzle.dir/Solver.cpp.o
.PHONY : Solver.cpp.o

Solver.i: Solver.cpp.i

.PHONY : Solver.i

# target to preprocess a source file
Solver.cpp.i:
	$(MAKE) -f CMakeFiles/npuzzle.dir/build.make CMakeFiles/npuzzle.dir/Solver.cpp.i
.PHONY : Solver.cpp.i

Solver.s: Solver.cpp.s

.PHONY : Solver.s

# target to generate assembly for a file
Solver.cpp.s:
	$(MAKE) -f CMakeFiles/npuzzle.dir/build.make CMakeFiles/npuzzle.dir/Solver.cpp.s
.PHONY : Solver.cpp.s

State.o: State.cpp.o

.PHONY : State.o

# target to build an object file
State.cpp.o:
	$(MAKE) -f CMakeFiles/npuzzle.dir/build.make CMakeFiles/npuzzle.dir/State.cpp.o
.PHONY : State.cpp.o

State.i: State.cpp.i

.PHONY : State.i

# target to preprocess a source file
State.cpp.i:
	$(MAKE) -f CMakeFiles/npuzzle.dir/build.make CMakeFiles/npuzzle.dir/State.cpp.i
.PHONY : State.cpp.i

State.s: State.cpp.s

.PHONY : State.s

# target to generate assembly for a file
State.cpp.s:
	$(MAKE) -f CMakeFiles/npuzzle.dir/build.make CMakeFiles/npuzzle.dir/State.cpp.s
.PHONY : State.cpp.s

Types.o: Types.cpp.o

.PHONY : Types.o

# target to build an object file
Types.cpp.o:
	$(MAKE) -f CMakeFiles/npuzzle.dir/build.make CMakeFiles/npuzzle.dir/Types.cpp.o
.PHONY : Types.cpp.o

Types.i: Types.cpp.i

.PHONY : Types.i

# target to preprocess a source file
Types.cpp.i:
	$(MAKE) -f CMakeFiles/npuzzle.dir/build.make CMakeFiles/npuzzle.dir/Types.cpp.i
.PHONY : Types.cpp.i

Types.s: Types.cpp.s

.PHONY : Types.s

# target to generate assembly for a file
Types.cpp.s:
	$(MAKE) -f CMakeFiles/npuzzle.dir/build.make CMakeFiles/npuzzle.dir/Types.cpp.s
.PHONY : Types.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/npuzzle.dir/build.make CMakeFiles/npuzzle.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/npuzzle.dir/build.make CMakeFiles/npuzzle.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/npuzzle.dir/build.make CMakeFiles/npuzzle.dir/main.cpp.s
.PHONY : main.cpp.s

tools.o: tools.cpp.o

.PHONY : tools.o

# target to build an object file
tools.cpp.o:
	$(MAKE) -f CMakeFiles/npuzzle.dir/build.make CMakeFiles/npuzzle.dir/tools.cpp.o
.PHONY : tools.cpp.o

tools.i: tools.cpp.i

.PHONY : tools.i

# target to preprocess a source file
tools.cpp.i:
	$(MAKE) -f CMakeFiles/npuzzle.dir/build.make CMakeFiles/npuzzle.dir/tools.cpp.i
.PHONY : tools.cpp.i

tools.s: tools.cpp.s

.PHONY : tools.s

# target to generate assembly for a file
tools.cpp.s:
	$(MAKE) -f CMakeFiles/npuzzle.dir/build.make CMakeFiles/npuzzle.dir/tools.cpp.s
.PHONY : tools.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... npuzzle"
	@echo "... CliOptParser.o"
	@echo "... CliOptParser.i"
	@echo "... CliOptParser.s"
	@echo "... Heuristics.o"
	@echo "... Heuristics.i"
	@echo "... Heuristics.s"
	@echo "... Solver.o"
	@echo "... Solver.i"
	@echo "... Solver.s"
	@echo "... State.o"
	@echo "... State.i"
	@echo "... State.s"
	@echo "... Types.o"
	@echo "... Types.i"
	@echo "... Types.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... tools.o"
	@echo "... tools.i"
	@echo "... tools.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

